In [1]:
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.utils import shuffle
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import numpy as np
from sklearn import preprocessing
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import scipy


read data

In [2]:
data = pd.read_csv('F:\leukemi_microarray\Leukemia_GSE9476.csv')

In [3]:
df = pd.DataFrame(data)
df = df.drop(columns=['samples'])

In [4]:
df = shuffle(df)
df.head(10)

type  1007_s_at   1053_at    117_at    121_at  1255_g_at  \
17       Bone_Marrow   7.813454  6.794223  6.576484  8.904530   4.506871   
25               AML   7.662544  7.352310  7.607587  8.694334   4.386515   
14       Bone_Marrow   7.892896  6.538820  6.673375  8.887987   4.359906   
13       Bone_Marrow   7.720314  6.583612  6.756619  8.845196   4.477831   
48                PB   8.104750  6.212916  9.229483  8.968546   4.566027   
8        Bone_Marrow   7.966060  6.781246  6.920990  8.978862   4.478028   
9        Bone_Marrow   7.692476  6.775148  6.616971  8.706216   4.443770   
31               AML   7.833074  6.444448  6.422178  8.866566   4.642514   
32               AML   7.765633  6.561750  6.733191  8.864177   4.568688   
4   Bone_Marrow_CD34   8.010117  7.405281  6.656049  9.050682   4.514986   

     1294_at   1316_at   1320_at  1405_i_at  ...  AFFX-r2-Hs28SrRNA-5_at  \
17  7.893402  5.532314  4.558692   8.601630  ...                4.620766   
25  7.663462  5.555711  4.658772   5.430714  ...                4.633553   
14  7.972636  5.473035  4.785807   8.389563  ...                4.880272   
13  8.064107  5.539644  4.537853   7.226976  ...                5.191044   
48  7.722725  5.661172  4.832844   7.742639  ...                4.313892   
8   7.683032  5.610469  4.824193   7.502364  ...                4.742075   
9   7.692134  5.501473  4.558013   9.985429  ...                5.082368   
31  8.171570  5.619711  4.664392   5.976281  ...                4.908617   
32  8.329480  5.500327  4.674511   5.790804  ...                5.000191   
4   8.377046  5.493713  4.860754   5.245049  ...                5.305192   

    AFFX-r2-Hs28SrRNA-M_at  AFFX-r2-P1-cre-3_at  AFFX-r2-P1-cre-5_at  \
17                6.573429            12.562943            12.435309   
25                6.085707            12.580625            12.557963   
14                6.483972            12.994929            13.036519   
13                6.824745            13.123380            13.057701   
48                6.209274            13.256962            13.003892   
8                 6.794769            13.524380            13.400021   
9                 6.913332            12.511607            12.470305   
31                6.919148            12.889525            12.586034   
32                6.646477            12.707219            12.559549   
4                 6.700453            12.949352            12.782515   

    AFFX-ThrX-3_at  AFFX-ThrX-5_at  AFFX-ThrX-M_at  AFFX-TrpnX-3_at  \
17        5.339725        4.535060        3.864028         3.576569   
25        5.212672        4.553464        3.855921         3.655604   
14        5.231631        4.602278        3.814854         3.581013   
13        5.230581        4.416719        3.890692         3.551122   
48        5.290075        4.514481        3.946614         3.602132   
8         5.327728        4.631000        3.897626         3.671963   
9         5.224274        4.517029        3.844456         3.587143   
31        5.577722        4.555417        3.939002         3.558659   
32        5.439620        4.661590        3.933793         3.686490   
4         5.341689        4.560315        3.887020         3.629853   

    AFFX-TrpnX-5_at  AFFX-TrpnX-M_at  
17         4.081583         3.985984  
25         4.139994         4.046524  
14         4.080418         4.073512  
13         4.097900         3.976198  
48         4.206121         4.103831  
8          4.002604         4.058350  
9          4.119111         3.985250  
31         4.133050         4.331262  
32         4.116434         4.041620  
4          4.127513         4.004316  

[10 rows x 22284 columns]

In [5]:
labels_count = df['type'].value_counts()
print(labels_count)

type
AML                 26
Bone_Marrow         10
PB                  10
PBSC_CD34           10
Bone_Marrow_CD34     8
Name: count, dtype: int64


In [6]:
label_encoder = LabelEncoder()
df.iloc[:, 0] = label_encoder.fit_transform(df.iloc[:, 0].values)
df.head(10)

type  1007_s_at   1053_at    117_at    121_at  1255_g_at   1294_at  \
17    1   7.813454  6.794223  6.576484  8.904530   4.506871  7.893402   
25    0   7.662544  7.352310  7.607587  8.694334   4.386515  7.663462   
14    1   7.892896  6.538820  6.673375  8.887987   4.359906  7.972636   
13    1   7.720314  6.583612  6.756619  8.845196   4.477831  8.064107   
48    3   8.104750  6.212916  9.229483  8.968546   4.566027  7.722725   
8     1   7.966060  6.781246  6.920990  8.978862   4.478028  7.683032   
9     1   7.692476  6.775148  6.616971  8.706216   4.443770  7.692134   
31    0   7.833074  6.444448  6.422178  8.866566   4.642514  8.171570   
32    0   7.765633  6.561750  6.733191  8.864177   4.568688  8.329480   
4     2   8.010117  7.405281  6.656049  9.050682   4.514986  8.377046   

     1316_at   1320_at  1405_i_at  ...  AFFX-r2-Hs28SrRNA-5_at  \
17  5.532314  4.558692   8.601630  ...                4.620766   
25  5.555711  4.658772   5.430714  ...                4.633553   
14  5.473035  4.785807   8.389563  ...                4.880272   
13  5.539644  4.537853   7.226976  ...                5.191044   
48  5.661172  4.832844   7.742639  ...                4.313892   
8   5.610469  4.824193   7.502364  ...                4.742075   
9   5.501473  4.558013   9.985429  ...                5.082368   
31  5.619711  4.664392   5.976281  ...                4.908617   
32  5.500327  4.674511   5.790804  ...                5.000191   
4   5.493713  4.860754   5.245049  ...                5.305192   

    AFFX-r2-Hs28SrRNA-M_at  AFFX-r2-P1-cre-3_at  AFFX-r2-P1-cre-5_at  \
17                6.573429            12.562943            12.435309   
25                6.085707            12.580625            12.557963   
14                6.483972            12.994929            13.036519   
13                6.824745            13.123380            13.057701   
48                6.209274            13.256962            13.003892   
8                 6.794769            13.524380            13.400021   
9                 6.913332            12.511607            12.470305   
31                6.919148            12.889525            12.586034   
32                6.646477            12.707219            12.559549   
4                 6.700453            12.949352            12.782515   

    AFFX-ThrX-3_at  AFFX-ThrX-5_at  AFFX-ThrX-M_at  AFFX-TrpnX-3_at  \
17        5.339725        4.535060        3.864028         3.576569   
25        5.212672        4.553464        3.855921         3.655604   
14        5.231631        4.602278        3.814854         3.581013   
13        5.230581        4.416719        3.890692         3.551122   
48        5.290075        4.514481        3.946614         3.602132   
8         5.327728        4.631000        3.897626         3.671963   
9         5.224274        4.517029        3.844456         3.587143   
31        5.577722        4.555417        3.939002         3.558659   
32        5.439620        4.661590        3.933793         3.686490   
4         5.341689        4.560315        3.887020         3.629853   

    AFFX-TrpnX-5_at  AFFX-TrpnX-M_at  
17         4.081583         3.985984  
25         4.139994         4.046524  
14         4.080418         4.073512  
13         4.097900         3.976198  
48         4.206121         4.103831  
8          4.002604         4.058350  
9          4.119111         3.985250  
31         4.133050         4.331262  
32         4.116434         4.041620  
4          4.127513         4.004316  

[10 rows x 22284 columns]

In [7]:
df.iloc[:, 1:] = np.log2(df.iloc[:, 1:].values)
df.head(10)

type  1007_s_at   1053_at    117_at    121_at  1255_g_at   1294_at  \
17    1   2.965960  2.764308  2.717316  3.154539   2.172126  2.980647   
25    0   2.937823  2.878198  2.927439  3.120076   2.133075  2.937996   
14    1   2.980555  2.709030  2.738417  3.151857   2.124297  2.995057   
13    1   2.948660  2.718879  2.756302  3.144894   2.162800  3.011515   
48    3   3.018768  2.635271  3.206250  3.164874   2.190939  2.949110   
8     1   2.993866  2.761550  2.790978  3.166533   2.162864  2.941676   
9     1   2.943448  2.760252  2.726171  3.122046   2.151784  2.943384   
31    0   2.969579  2.688057  2.683063  3.148375   2.214906  3.030613   
32    0   2.957103  2.714081  2.751290  3.147987   2.191780  3.058226   
4     2   3.001823  2.888555  2.734666  3.178026   2.174721  3.066442   

     1316_at   1320_at  1405_i_at  ...  AFFX-r2-Hs28SrRNA-5_at  \
17  2.467883  2.188620   3.104610  ...                2.208132   
25  2.473971  2.219950   2.441142  ...                2.212119   
14  2.452341  2.258762   3.068596  ...                2.286962   
13  2.469793  2.182010   2.853392  ...                2.376025   
48  2.501101  2.272872   2.952825  ...                2.108990   
8   2.488121  2.270287   2.907345  ...                2.245518   
9   2.459818  2.188405   3.319824  ...                2.345501   
31  2.490496  2.221689   2.579248  ...                2.295317   
32  2.459518  2.224815   2.533764  ...                2.321983   
4   2.457782  2.281180   2.390956  ...                2.407405   

    AFFX-r2-Hs28SrRNA-M_at  AFFX-r2-P1-cre-3_at  AFFX-r2-P1-cre-5_at  \
17                2.716646             3.651103             3.636370   
25                2.605425             3.653132             3.650531   
14                2.696878             3.699877             3.704487   
13                2.770775             3.714067             3.706829   
48                2.634425             3.728678             3.700872   
8                 2.764424             3.757491             3.744163   
9                 2.789381             3.645195             3.640425   
31                2.790594             3.688127             3.653752   
32                2.732590             3.667576             3.650713   
4                 2.744259             3.694808             3.676100   

    AFFX-ThrX-3_at  AFFX-ThrX-5_at  AFFX-ThrX-M_at  AFFX-TrpnX-3_at  \
17        2.416765        2.181122        1.950105         1.838576   
25        2.382023        2.186965        1.947075         1.870110   
14        2.387261        2.202348        1.931628         1.840368   
13        2.386971        2.142975        1.960027         1.828275   
48        2.403288        2.174560        1.980615         1.848851   
8         2.413520        2.211324        1.962596         1.876552   
9         2.385230        2.175374        1.942780         1.842835   
31        2.479676        2.187583        1.977830         1.831334   
32        2.443506        2.220822        1.975921         1.882248   
4         2.417296        2.189133        1.958665         1.859911   

    AFFX-TrpnX-5_at  AFFX-TrpnX-M_at  
17         2.029129         1.994936  
25         2.049629         2.016683  
14         2.028717         2.026273  
13         2.034885         1.991390  
48         2.072490         2.036971  
8          2.000939         2.020893  
9          2.042333         1.994670  
31         2.047207         2.114787  
32         2.041395         2.014934  
4          2.045273         2.001556  

[10 rows x 22284 columns]

In [8]:
X = df.iloc[:, 1:]
y = df['type']
y

17    1
25    0
14    1
13    1
48    3
     ..
36    0
29    0
62    4
61    4
53    3
Name: type, Length: 64, dtype: object

In [9]:
y = y.astype('int')
(X_train, X_test, y_train, y_test) = train_test_split(X, y, test_size=0.33, random_state=42)

In [10]:
sc=StandardScaler()
X_train = pd.DataFrame(sc.fit_transform(X_train.values), columns=X_train.columns)
X_test = sc.fit_transform(X_test.values)

SVM

In [11]:
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline

In [12]:
svm_model = SVC(probability=True)

In [13]:
svm_model.fit(X_train, y_train)

SVC(probability=True)

In [14]:
svm_pred = svm_model.predict(X_test)

f:\leukemi_microarray\.venv\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [15]:
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score

In [16]:
print(confusion_matrix(y_test, svm_pred))

[[8 0 0 0 0]
 [1 3 0 0 0]
 [4 0 0 0 0]
 [0 0 0 2 0]
 [1 0 0 0 3]]


In [17]:
test_accuracy= accuracy_score(y_test, svm_pred)
test_accuracy * 100

72.72727272727273

In [18]:
train_accuracy = accuracy_score(y_train, svm_model.predict(X_train))
train_accuracy * 100

100.0

In [19]:
from sklearn.metrics import f1_score
f1_score(y_test, svm_pred, average='micro')

0.7272727272727273

In [20]:
print(classification_report(y_test, svm_pred))

              precision    recall  f1-score   support

           0       0.57      1.00      0.73         8
           1       1.00      0.75      0.86         4
           2       0.00      0.00      0.00         4
           3       1.00      1.00      1.00         2
           4       1.00      0.75      0.86         4

    accuracy                           0.73        22
   macro avg       0.71      0.70      0.69        22
weighted avg       0.66      0.73      0.67        22



f:\leukemi_microarray\.venv\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
f:\leukemi_microarray\.venv\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
f:\leukemi_microarray\.venv\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Logistic Regression

In [21]:
from sklearn.linear_model import LogisticRegression

In [22]:
lg_model = LogisticRegression().fit(X_train, y_train)

f:\leukemi_microarray\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [23]:
lg_predict = lg_model.predict(X_test)

f:\leukemi_microarray\.venv\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [24]:
lg_train_accuracy = accuracy_score(y_train, lg_model.predict(X_train))
lg_train_accuracy

1.0

In [25]:
lg_test_accuracy = accuracy_score(y_test, lg_predict)
lg_test_accuracy

1.0

In [26]:
print(classification_report(y_test, lg_predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00         4
           2       1.00      1.00      1.00         4
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         4

    accuracy                           1.00        22
   macro avg       1.00      1.00      1.00        22
weighted avg       1.00      1.00      1.00        22



Linear Discriminant Analysis

In [27]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [28]:
ld = LinearDiscriminantAnalysis().fit(X_train, y_train)

In [29]:
ld_predict = ld.predict(X_test)

f:\leukemi_microarray\.venv\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearDiscriminantAnalysis was fitted with feature names
  warnings.warn(


In [30]:
ld_test_accuracy_score = accuracy_score(y_test, ld_predict)
ld_test_accuracy_score 

0.9545454545454546

In [31]:
ld_train_accuracy_score = accuracy_score(y_train, ld.predict(X_train))
ld_train_accuracy_score * 100

88.09523809523809

In [32]:
print(classification_report(y_test, ld_predict))

              precision    recall  f1-score   support

           0       0.89      1.00      0.94         8
           1       1.00      1.00      1.00         4
           2       1.00      1.00      1.00         4
           3       1.00      1.00      1.00         2
           4       1.00      0.75      0.86         4

    accuracy                           0.95        22
   macro avg       0.98      0.95      0.96        22
weighted avg       0.96      0.95      0.95        22



Random Forest

In [33]:
from sklearn.ensemble import RandomForestClassifier

In [34]:
rf = RandomForestClassifier().fit(X_train, y_train)

In [35]:
rf_pred = rf.predict(X_test)

f:\leukemi_microarray\.venv\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [36]:
rf_train_accuracy = accuracy_score(y_train, rf.predict(X_train))
rf_train_accuracy

1.0

In [37]:
rf_test_accuracy = accuracy_score(y_test, rf_pred)
rf_test_accuracy * 100

90.9090909090909

naive bayes

In [38]:
from sklearn.naive_bayes import GaussianNB

In [39]:
nb = GaussianNB().fit(X_train, y_train)

In [40]:
nb_pred = nb.predict(X_test)

f:\leukemi_microarray\.venv\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


In [41]:
print("Accuracy: ", accuracy_score(y_test, nb_pred)*100)

Accuracy:  50.0


In [42]:
nb_train_accuracy = accuracy_score(y_train, nb.predict(X_train))
nb_train_accuracy

1.0

Logistic Regression

In [43]:
from sklearn.linear_model import LogisticRegression

In [44]:
lgreg = LogisticRegression().fit(X_train, y_train)

f:\leukemi_microarray\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [45]:
lgreg_predict = lgreg.predict(X_test)

f:\leukemi_microarray\.venv\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [46]:
log_reg_test_accuracy = accuracy_score(y_test, lgreg_predict)
log_reg_test_accuracy

1.0

In [47]:
log_reg_train_accuracy = accuracy_score(y_train, lgreg.predict(X_train))
log_reg_train_accuracy

1.0

In [48]:
print(classification_report(y_test, lgreg_predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00         4
           2       1.00      1.00      1.00         4
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         4

    accuracy                           1.00        22
   macro avg       1.00      1.00      1.00        22
weighted avg       1.00      1.00      1.00        22



In [49]:
print(confusion_matrix(y_test, lgreg_predict))

[[8 0 0 0 0]
 [0 4 0 0 0]
 [0 0 4 0 0]
 [0 0 0 2 0]
 [0 0 0 0 4]]
