# import libraries

In [64]:
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.utils import shuffle
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import numpy as np
from sklearn import preprocessing
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score

In [65]:
data = pd.read_csv('F:\leukemi_microarray\Leukemia_GSE9476.csv')

In [66]:
data.head(10)

samples              type  1007_s_at   1053_at     117_at    121_at  \
0        1  Bone_Marrow_CD34   7.745245  7.811210   6.477916  8.841506   
1       12  Bone_Marrow_CD34   8.087252  7.240673   8.584648  8.983571   
2       13  Bone_Marrow_CD34   7.792056  7.549368  11.053504  8.909703   
3       14  Bone_Marrow_CD34   7.767265  7.094460  11.816433  8.994654   
4       15  Bone_Marrow_CD34   8.010117  7.405281   6.656049  9.050682   
5       16  Bone_Marrow_CD34   7.830279  7.025275   7.193019  9.114221   
6       17  Bone_Marrow_CD34   8.167701  6.949900   7.604404  9.326422   
7       18  Bone_Marrow_CD34   7.712012  7.962858  10.549554  9.071372   
8        2       Bone_Marrow   7.966060  6.781246   6.920990  8.978862   
9        3       Bone_Marrow   7.692476  6.775148   6.616971  8.706216   

   1255_g_at   1294_at   1316_at   1320_at  ...  AFFX-r2-Hs28SrRNA-5_at  \
0   4.546941  7.957714  5.344999  4.673364  ...                5.058849   
1   4.548934  8.011652  5.579647  4.828184  ...                4.436153   
2   4.549328  8.237099  5.406489  4.615572  ...                4.392061   
3   4.697018  8.283412  5.582195  4.903684  ...                4.633334   
4   4.514986  8.377046  5.493713  4.860754  ...                5.305192   
5   4.584802  8.205780  5.641085  4.765249  ...                4.250235   
6   4.754915  7.331400  5.908871  5.193624  ...                4.650690   
7   4.516647  8.111130  5.578826  4.757115  ...                4.643991   
8   4.478028  7.683032  5.610469  4.824193  ...                4.742075   
9   4.443770  7.692134  5.501473  4.558013  ...                5.082368   

   AFFX-r2-Hs28SrRNA-M_at  AFFX-r2-P1-cre-3_at  AFFX-r2-P1-cre-5_at  \
0                6.810004            12.800060            12.718612   
1                6.751471            12.472706            12.333593   
2                6.086295            12.637384            12.499038   
3                6.375991            12.903630            12.871454   
4                6.700453            12.949352            12.782515   
5                6.155386            13.292661            13.234471   
6                6.836679            13.239335            13.024450   
7                6.412188            12.761211            12.515943   
8                6.794769            13.524380            13.400021   
9                6.913332            12.511607            12.470305   

   AFFX-ThrX-3_at  AFFX-ThrX-5_at  AFFX-ThrX-M_at  AFFX-TrpnX-3_at  \
0        5.391512        4.666166        3.974759         3.656693   
1        5.379738        4.656786        4.188348         3.792535   
2        5.316604        4.600566        3.845561         3.635715   
3        5.179951        4.641952        3.991634         3.704587   
4        5.341689        4.560315        3.887020         3.629853   
5        5.250568        4.605257        3.864205         3.735947   
6        5.635133        4.831326        4.118359         3.676294   
7        5.284926        4.690645        3.824535         3.552306   
8        5.327728        4.631000        3.897626         3.671963   
9        5.224274        4.517029        3.844456         3.587143   

   AFFX-TrpnX-5_at  AFFX-TrpnX-M_at  
0         4.160622         4.139249  
1         4.204414         4.122700  
2         4.174199         4.067152  
3         4.149938         3.910150  
4         4.127513         4.004316  
5         4.109941         4.139532  
6         4.290143         4.232628  
7         4.069378         4.083583  
8         4.002604         4.058350  
9         4.119111         3.985250  

[10 rows x 22285 columns]

In [67]:
df = pd.DataFrame(data)

In [68]:
df = df.drop(columns=['samples'])

In [69]:
df = shuffle(df)
df.head(10)

type  1007_s_at   1053_at    117_at    121_at  1255_g_at  \
38               AML   7.472371  6.992946  7.054268  8.535614   4.378798   
17       Bone_Marrow   7.813454  6.794223  6.576484  8.904530   4.506871   
10       Bone_Marrow   7.672274  6.745299  6.666445  8.735914   4.474554   
0   Bone_Marrow_CD34   7.745245  7.811210  6.477916  8.841506   4.546941   
57         PBSC_CD34   7.573025  6.825199  6.494179  8.898793   4.356424   
40               AML   7.278076  6.789870  6.296965  8.486306   4.371023   
52                PB   7.653021  6.446622  9.350849  8.679697   4.414988   
49                PB   8.021694  6.286823  8.952662  8.862089   4.585165   
62         PBSC_CD34   7.900992  6.787515  6.642927  8.856187   4.499548   
30               AML   7.648361  6.941281  6.681016  9.150922   4.567999   

     1294_at   1316_at   1320_at  1405_i_at  ...  AFFX-r2-Hs28SrRNA-5_at  \
38  8.017237  5.306567  4.558432   9.068472  ...                4.416250   
17  7.893402  5.532314  4.558692   8.601630  ...                4.620766   
10  7.782910  5.563327  4.599482   9.450355  ...                4.943018   
0   7.957714  5.344999  4.673364   4.664924  ...                5.058849   
57  8.720641  5.468922  4.645839   6.217313  ...                4.477162   
40  8.144421  5.295685  4.624420   8.909136  ...                5.073046   
52  8.501428  5.557493  4.777821   8.791383  ...                4.790587   
49  8.280266  5.777682  4.652564   8.708122  ...                4.622493   
62  9.188459  5.471110  4.637444   5.036441  ...                4.985061   
30  8.785498  5.554364  4.707020   5.871494  ...                4.551749   

    AFFX-r2-Hs28SrRNA-M_at  AFFX-r2-P1-cre-3_at  AFFX-r2-P1-cre-5_at  \
38                5.746084            12.605391            12.356229   
17                6.573429            12.562943            12.435309   
10                7.008125            12.719027            12.810575   
0                 6.810004            12.800060            12.718612   
57                6.162619            12.886991            12.765789   
40                6.838643            12.808871            12.707061   
52                6.563362            13.273002            12.976204   
49                6.267578            13.193406            12.789475   
62                6.815527            13.020089            12.824868   
30                6.583213            12.983395            12.772124   

    AFFX-ThrX-3_at  AFFX-ThrX-5_at  AFFX-ThrX-M_at  AFFX-TrpnX-3_at  \
38        5.037287        4.438082        3.803410         3.635785   
17        5.339725        4.535060        3.864028         3.576569   
10        5.269983        4.445377        3.867552         3.593237   
0         5.391512        4.666166        3.974759         3.656693   
57        5.104438        4.431385        3.812532         3.608116   
40        5.297992        4.568786        3.829237         3.638288   
52        5.400082        4.561398        3.910235         3.675136   
49        5.220769        4.535342        3.929496         3.691120   
62        5.459571        4.602105        4.019624         3.570563   
30        5.174411        4.551217        3.977818         3.672945   

    AFFX-TrpnX-5_at  AFFX-TrpnX-M_at  
38         4.090078         4.133423  
17         4.081583         3.985984  
10         4.127582         4.082404  
0          4.160622         4.139249  
57         4.002839         4.016314  
40         4.004818         4.024601  
52         4.135808         4.074108  
49         4.200518         4.158051  
62         4.141371         4.102641  
30         4.165100         4.144287  

[10 rows x 22284 columns]

In [70]:
df = df.dropna(axis=1)
df = df.dropna()

In [71]:
labels_count = df['type'].value_counts()
print(labels_count)

type
AML                 26
Bone_Marrow         10
PBSC_CD34           10
PB                  10
Bone_Marrow_CD34     8
Name: count, dtype: int64


In [72]:
label_encoder = LabelEncoder()

In [73]:
df.iloc[:, 0] = label_encoder.fit_transform(df.iloc[:, 0].values)
df.head(10)

type  1007_s_at   1053_at    117_at    121_at  1255_g_at   1294_at  \
38    0   7.472371  6.992946  7.054268  8.535614   4.378798  8.017237   
17    1   7.813454  6.794223  6.576484  8.904530   4.506871  7.893402   
10    1   7.672274  6.745299  6.666445  8.735914   4.474554  7.782910   
0     2   7.745245  7.811210  6.477916  8.841506   4.546941  7.957714   
57    4   7.573025  6.825199  6.494179  8.898793   4.356424  8.720641   
40    0   7.278076  6.789870  6.296965  8.486306   4.371023  8.144421   
52    3   7.653021  6.446622  9.350849  8.679697   4.414988  8.501428   
49    3   8.021694  6.286823  8.952662  8.862089   4.585165  8.280266   
62    4   7.900992  6.787515  6.642927  8.856187   4.499548  9.188459   
30    0   7.648361  6.941281  6.681016  9.150922   4.567999  8.785498   

     1316_at   1320_at  1405_i_at  ...  AFFX-r2-Hs28SrRNA-5_at  \
38  5.306567  4.558432   9.068472  ...                4.416250   
17  5.532314  4.558692   8.601630  ...                4.620766   
10  5.563327  4.599482   9.450355  ...                4.943018   
0   5.344999  4.673364   4.664924  ...                5.058849   
57  5.468922  4.645839   6.217313  ...                4.477162   
40  5.295685  4.624420   8.909136  ...                5.073046   
52  5.557493  4.777821   8.791383  ...                4.790587   
49  5.777682  4.652564   8.708122  ...                4.622493   
62  5.471110  4.637444   5.036441  ...                4.985061   
30  5.554364  4.707020   5.871494  ...                4.551749   

    AFFX-r2-Hs28SrRNA-M_at  AFFX-r2-P1-cre-3_at  AFFX-r2-P1-cre-5_at  \
38                5.746084            12.605391            12.356229   
17                6.573429            12.562943            12.435309   
10                7.008125            12.719027            12.810575   
0                 6.810004            12.800060            12.718612   
57                6.162619            12.886991            12.765789   
40                6.838643            12.808871            12.707061   
52                6.563362            13.273002            12.976204   
49                6.267578            13.193406            12.789475   
62                6.815527            13.020089            12.824868   
30                6.583213            12.983395            12.772124   

    AFFX-ThrX-3_at  AFFX-ThrX-5_at  AFFX-ThrX-M_at  AFFX-TrpnX-3_at  \
38        5.037287        4.438082        3.803410         3.635785   
17        5.339725        4.535060        3.864028         3.576569   
10        5.269983        4.445377        3.867552         3.593237   
0         5.391512        4.666166        3.974759         3.656693   
57        5.104438        4.431385        3.812532         3.608116   
40        5.297992        4.568786        3.829237         3.638288   
52        5.400082        4.561398        3.910235         3.675136   
49        5.220769        4.535342        3.929496         3.691120   
62        5.459571        4.602105        4.019624         3.570563   
30        5.174411        4.551217        3.977818         3.672945   

    AFFX-TrpnX-5_at  AFFX-TrpnX-M_at  
38         4.090078         4.133423  
17         4.081583         3.985984  
10         4.127582         4.082404  
0          4.160622         4.139249  
57         4.002839         4.016314  
40         4.004818         4.024601  
52         4.135808         4.074108  
49         4.200518         4.158051  
62         4.141371         4.102641  
30         4.165100         4.144287  

[10 rows x 22284 columns]

In [74]:
df.iloc[:, 1:] = np.log2(df.iloc[:, 1:].values)

In [75]:
df.head(10)

type  1007_s_at   1053_at    117_at    121_at  1255_g_at   1294_at  \
38    0   2.901566  2.805900  2.818496  3.093495   2.130535  3.003105   
17    1   2.965960  2.764308  2.717316  3.154539   2.172126  2.980647   
10    1   2.939654  2.753882  2.736918  3.126959   2.161744  2.960310   
0     2   2.953311  2.965546  2.695530  3.144292   2.184896  2.992354   
57    4   2.920870  2.770871  2.699147  3.153610   2.123144  3.124434   
40    0   2.863557  2.763384  2.654657  3.085137   2.127971  3.025812   
52    3   2.936029  2.688543  3.225097  3.117645   2.142410  3.087705   
49    3   3.003907  2.652331  3.162317  3.147647   2.196974  3.049677   
62    4   2.982034  2.762883  2.731819  3.146686   2.169780  3.199823   
30    0   2.935151  2.795202  2.740067  3.193917   2.191562  3.135124   

     1316_at   1320_at  1405_i_at  ...  AFFX-r2-Hs28SrRNA-5_at  \
38  2.407779  2.188538   3.180859  ...                2.142822   
17  2.467883  2.188620   3.104610  ...                2.208132   
10  2.475948  2.201471   3.240369  ...                2.305392   
0   2.418190  2.224461   2.221854  ...                2.338809   
57  2.451257  2.215939   2.636291  ...                2.162585   
40  2.404817  2.209272   3.155285  ...                2.342852   
52  2.474434  2.256353   3.136090  ...                2.260202   
49  2.530491  2.218026   3.122362  ...                2.208671   
62  2.451834  2.213330   2.332405  ...                2.317611   
30  2.473622  2.234814   2.553728  ...                2.186421   

    AFFX-r2-Hs28SrRNA-M_at  AFFX-r2-P1-cre-3_at  AFFX-r2-P1-cre-5_at  \
38                2.522579             3.655969             3.627167   
17                2.716646             3.651103             3.636370   
10                2.809028             3.668916             3.679263   
0                 2.767656             3.678079             3.668869   
57                2.623543             3.687844             3.674211   
40                2.773710             3.679071             3.667558   
52                2.714435             3.730423             3.697796   
49                2.647908             3.721745             3.676885   
62                2.768825             3.702667             3.680872   
30                2.718792             3.698596             3.674927   

    AFFX-ThrX-3_at  AFFX-ThrX-5_at  AFFX-ThrX-M_at  AFFX-TrpnX-3_at  \
38        2.332647        2.149936        1.927293         1.862267   
17        2.416765        2.181122        1.950105         1.838576   
10        2.397798        2.152306        1.951421         1.845284   
0         2.430690        2.222238        1.990868         1.870540   
57        2.351752        2.147758        1.930749         1.851246   
40        2.405446        2.191811        1.937057         1.863260   
52        2.432981        2.189476        1.967255         1.877798   
49        2.384262        2.181211        1.974344         1.884059   
62        2.448788        2.202294        2.007061         1.836152   
30        2.371395        2.186252        1.991977         1.876937   

    AFFX-TrpnX-5_at  AFFX-TrpnX-M_at  
38         2.032128         2.047337  
17         2.029129         1.994936  
10         2.045297         2.029419  
0          2.056799         2.049369  
57         2.001024         2.005872  
40         2.001737         2.008846  
52         2.048169         2.026484  
49         2.070567         2.055907  
62         2.050108         2.036553  
30         2.058351         2.051124  

[10 rows x 22284 columns]

In [76]:
df.to_csv('transformed_data.csv')

In [77]:
X = df.iloc[:, 1:]
print(X)

    1007_s_at   1053_at    117_at    121_at  1255_g_at   1294_at   1316_at  \
38   2.901566  2.805900  2.818496  3.093495   2.130535  3.003105  2.407779   
17   2.965960  2.764308  2.717316  3.154539   2.172126  2.980647  2.467883   
10   2.939654  2.753882  2.736918  3.126959   2.161744  2.960310  2.475948   
0    2.953311  2.965546  2.695530  3.144292   2.184896  2.992354  2.418190   
57   2.920870  2.770871  2.699147  3.153610   2.123144  3.124434  2.451257   
..        ...       ...       ...       ...        ...       ...       ...   
8    2.993866  2.761550  2.790978  3.166533   2.162864  2.941676  2.488121   
9    2.943448  2.760252  2.726171  3.122046   2.151784  2.943384  2.459818   
29   2.939599  2.726706  2.771574  3.149820   2.132537  3.079344  2.415917   
4    3.001823  2.888555  2.734666  3.178026   2.174721  3.066442  2.457782   
34   2.919436  2.675147  2.795723  3.163801   2.174017  3.181552  2.431451   

     1320_at  1405_i_at   1431_at  ...  AFFX-r2-Hs28SrRNA-5_at 

In [78]:
y = df['type']
y.astype('int')
print(y)

38    0
17    1
10    1
0     2
57    4
     ..
8     1
9     1
29    0
4     2
34    0
Name: type, Length: 64, dtype: object


One-way ANOVA test

In [79]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

In [80]:
df.head()

type  1007_s_at   1053_at    117_at    121_at  1255_g_at   1294_at  \
38    0   2.901566  2.805900  2.818496  3.093495   2.130535  3.003105   
17    1   2.965960  2.764308  2.717316  3.154539   2.172126  2.980647   
10    1   2.939654  2.753882  2.736918  3.126959   2.161744  2.960310   
0     2   2.953311  2.965546  2.695530  3.144292   2.184896  2.992354   
57    4   2.920870  2.770871  2.699147  3.153610   2.123144  3.124434   

     1316_at   1320_at  1405_i_at  ...  AFFX-r2-Hs28SrRNA-5_at  \
38  2.407779  2.188538   3.180859  ...                2.142822   
17  2.467883  2.188620   3.104610  ...                2.208132   
10  2.475948  2.201471   3.240369  ...                2.305392   
0   2.418190  2.224461   2.221854  ...                2.338809   
57  2.451257  2.215939   2.636291  ...                2.162585   

    AFFX-r2-Hs28SrRNA-M_at  AFFX-r2-P1-cre-3_at  AFFX-r2-P1-cre-5_at  \
38                2.522579             3.655969             3.627167   
17                2.716646             3.651103             3.636370   
10                2.809028             3.668916             3.679263   
0                 2.767656             3.678079             3.668869   
57                2.623543             3.687844             3.674211   

    AFFX-ThrX-3_at  AFFX-ThrX-5_at  AFFX-ThrX-M_at  AFFX-TrpnX-3_at  \
38        2.332647        2.149936        1.927293         1.862267   
17        2.416765        2.181122        1.950105         1.838576   
10        2.397798        2.152306        1.951421         1.845284   
0         2.430690        2.222238        1.990868         1.870540   
57        2.351752        2.147758        1.930749         1.851246   

    AFFX-TrpnX-5_at  AFFX-TrpnX-M_at  
38         2.032128         2.047337  
17         2.029129         1.994936  
10         2.045297         2.029419  
0          2.056799         2.049369  
57         2.001024         2.005872  

[5 rows x 22284 columns]

In [81]:
features = df.iloc[:, 1:].columns.values
features

array(['1007_s_at', '1053_at', '117_at', ..., 'AFFX-TrpnX-3_at',
       'AFFX-TrpnX-5_at', 'AFFX-TrpnX-M_at'], dtype=object)

In [82]:
y = y.astype('int')
(X_train, X_test, y_train, y_test) = train_test_split(X, y, test_size=0.33, random_state=42)
X_test

1007_s_at   1053_at    117_at    121_at  1255_g_at   1294_at   1316_at  \
11   2.953915  2.759384  2.733615  3.119330   2.166927  2.993540  2.464148   
13   2.948660  2.718879  2.756302  3.144894   2.162800  3.011515  2.469793   
38   2.901566  2.805900  2.818496  3.093495   2.130535  3.003105  2.407779   
28   2.914474  2.803349  2.714531  3.109781   2.170046  3.262374  2.417563   
40   2.863557  2.763384  2.654657  3.085137   2.127971  3.025812  2.404817   
21   2.945618  2.713712  3.274227  3.160615   2.189523  2.973877  2.480697   
47   2.968920  2.743413  3.190956  3.096810   2.187349  3.034124  2.513344   
45   2.959939  2.744926  3.224181  3.126680   2.126224  3.040950  2.465065   
25   2.937823  2.878198  2.927439  3.120076   2.133075  2.937996  2.473971   
29   2.939599  2.726706  2.771574  3.149820   2.132537  3.079344  2.415917   
39   2.989002  2.727488  2.763437  3.125731   2.162261  3.100184  2.427548   
30   2.935151  2.795202  2.740067  3.193917   2.191562  3.135124  2.473622   
61   2.975097  2.785810  2.729159  3.133422   2.156412  3.115119  2.479566   
6    3.029930  2.796992  2.926835  3.221324   2.249420  2.874089  2.562882   
33   2.956168  2.703021  2.765153  3.179725   2.159318  3.017494  2.525621   
42   2.996210  2.791871  2.738270  3.213076   2.191381  3.105360  2.513369   
0    2.953311  2.965546  2.695530  3.144292   2.184896  2.992354  2.418190   
56   2.949871  2.834432  2.724008  3.117318   2.121407  3.094002  2.417656   
19   3.002890  2.763935  2.832879  3.159417   2.180324  3.041293  2.448340   
62   2.982034  2.762883  2.731819  3.146686   2.169780  3.199823  2.451834   
52   2.936029  2.688543  3.225097  3.117645   2.142410  3.087705  2.474434   
54   2.985808  2.723444  2.751013  3.187095   2.163484  3.150845  2.448351   

     1320_at  1405_i_at   1431_at  ...  AFFX-r2-Hs28SrRNA-5_at  \
11  2.212718   3.037368  2.022117  ...                2.397274   
13  2.182010   2.853392  2.007794  ...                2.376025   
38  2.188538   3.180859  1.987206  ...                2.142822   
28  2.201844   2.709862  2.059499  ...                2.340271   
40  2.209272   3.155285  2.007907  ...                2.342852   
21  2.249622   2.870250  2.050909  ...                2.298453   
47  2.267656   2.804679  2.128501  ...                2.448353   
45  2.217561   3.038613  2.098311  ...                2.308263   
25  2.219950   2.441142  2.003267  ...                2.212119   
29  2.242096   3.100886  2.011726  ...                2.286614   
39  2.207920   2.785321  2.037850  ...                2.145575   
30  2.234814   2.553728  2.048149  ...                2.186421   
61  2.279173   2.267806  2.041947  ...                2.340795   
6   2.376742   2.310935  2.113759  ...                2.217445   
33  2.293268   2.498226  2.068463  ...                2.309841   
42  2.288486   2.705267  2.078561  ...                2.171919   
0   2.224461   2.221854  2.024896  ...                2.338809   
56  2.264951   2.183962  2.020706  ...                2.271223   
19  2.211863   2.423119  1.961015  ...                2.252118   
62  2.213330   2.332405  2.049558  ...                2.317611   
52  2.256353   3.136090  2.007606  ...                2.260202   
54  2.213032   2.331975  2.068442  ...                2.345147   

    AFFX-r2-Hs28SrRNA-M_at  AFFX-r2-P1-cre-3_at  AFFX-r2-P1-cre-5_at  \
11                2.841166             3.672179             3.663946   
13                2.770775             3.714067             3.706829   
38                2.522579             3.655969             3.627167   
28                2.735407             3.684543             3.669717   
40                2.773710             3.679071             3.667558   
21                2.665156             3.696680             3.667404   
47                2.858456             3.667471             3.640352   
45                2.660147             3.723359             3.710576   
25                2.605425             3.6

In [83]:
sc=StandardScaler()
X_train = pd.DataFrame(sc.fit_transform(X_train.values), columns=X_train.columns)
X_test = pd.DataFrame(sc.fit_transform(X_test.values), columns=X_test.columns)

In [84]:
fs = SelectKBest(score_func=f_classif, k='all').fit(X_train, y_train)
features_score = pd.DataFrame(fs.scores_)
features_pvalue = pd.DataFrame(fs.pvalues_)
features = pd.DataFrame(X.columns)
features_score = pd.concat([features, features_score, features_pvalue], axis=1)
features_score.columns = ["Input_Features","F_score","P_Value"]
#features_score = features_score.iloc[:200, :]
features_score = features_score.sort_values('F_score').iloc[22200:, :]
features_score

Input_Features     F_score       P_Value
7807       208304_at   86.683010  2.854851e-18
12215      212831_at   87.130428  2.620607e-18
13106    213727_x_at   87.388886  2.494604e-18
17399    218035_s_at   87.479722  2.451850e-18
1033       201506_at   87.696082  2.353095e-18
...              ...         ...           ...
6533       207008_at  308.441841  7.317777e-28
9602       210119_at  313.814175  5.368508e-28
19550      220187_at  314.168831  5.260798e-28
10604    211163_s_at  322.537989  3.281655e-28
19035      219672_at  361.434247  4.233261e-29

[83 rows x 3 columns]

In [85]:
features_score.to_csv('top_features.csv')

In [86]:
y_train

57    4
15    1
51    3
37    0
20    0
35    0
32    0
41    0
8     1
9     1
16    1
46    3
5     2
14    1
58    4
60    4
44    3
59    4
22    0
55    4
1     2
3     2
48    3
17    1
12    1
10    1
4     2
31    0
50    3
36    0
27    0
2     2
7     2
23    0
34    0
63    4
49    3
18    0
43    0
24    0
53    3
26    0
Name: type, dtype: int32

In [134]:
important_features_extract = features_score.head(10).to_csv('features_extract.csv')
important_features_extract

In [ ]:
important_features = features_score.iloc[:, 0].to_list()
dt = df
important_features

In [ ]:
features_to_drop = [col for col in X_train.columns if col not in important_features]
X_train = X_train.drop(columns=features_to_drop)
X_test = X_test.drop(columns=features_to_drop)
X_test = sc.fit_transform(X_test.values)

In [126]:
X_test

array([[ 1.64686245,  0.01094922, -0.47363872, ..., -0.38357347,
         0.71541288, -0.43769124],
       [ 1.2260117 , -0.15607093, -0.18925784, ...,  0.02279624,
        -0.04661054, -0.35160698],
       [-0.33547846,  0.21242613, -0.75762606, ...,  0.15746915,
         0.0127407 , -0.53221138],
       ...,
       [-0.52764017,  0.11459844,  1.3327211 , ..., -0.41171058,
        -0.46039866, -0.43189869],
       [ 1.59559441,  3.08736196, -0.74703981, ...,  2.38355458,
         2.33659476,  2.78655851],
       [-0.39593189,  0.18684516,  1.74499683, ..., -0.55513281,
        -0.34232188, -0.18966504]])

Random Forest

In [89]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import ConfusionMatrixDisplay

In [90]:
rf = RandomForestClassifier().fit(X_train, y_train)

In [91]:
y_train.shape

(42,)

In [92]:
rf_pred = rf.predict(X_test)

f:\leukemi_microarray\.venv\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [93]:
rf_train_accuracy = accuracy_score(y_train, rf.predict(X_train))
rf_train_accuracy

1.0

In [94]:
rf_test_accuracy = accuracy_score(y_test, rf_pred)
rf_test_accuracy * 100

95.45454545454545

In [95]:
print(confusion_matrix(y_test, rf_pred))

[[10  1  0  0  0]
 [ 0  2  0  0  0]
 [ 0  0  2  0  0]
 [ 0  0  0  3  0]
 [ 0  0  0  0  4]]


In [96]:
print(classification_report(y_test, rf_pred))

              precision    recall  f1-score   support

           0       1.00      0.91      0.95        11
           1       0.67      1.00      0.80         2
           2       1.00      1.00      1.00         2
           3       1.00      1.00      1.00         3
           4       1.00      1.00      1.00         4

    accuracy                           0.95        22
   macro avg       0.93      0.98      0.95        22
weighted avg       0.97      0.95      0.96        22



SVM

In [97]:
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline

In [98]:
print(features_score)

      Input_Features     F_score       P_Value
7807       208304_at   86.683010  2.854851e-18
12215      212831_at   87.130428  2.620607e-18
13106    213727_x_at   87.388886  2.494604e-18
17399    218035_s_at   87.479722  2.451850e-18
1033       201506_at   87.696082  2.353095e-18
...              ...         ...           ...
6533       207008_at  308.441841  7.317777e-28
9602       210119_at  313.814175  5.368508e-28
19550      220187_at  314.168831  5.260798e-28
10604    211163_s_at  322.537989  3.281655e-28
19035      219672_at  361.434247  4.233261e-29

[83 rows x 3 columns]


In [99]:
svm_model = SVC(probability=True).fit(X_train, y_train)

In [100]:
svm_pred = svm_model.predict(X_test)

f:\leukemi_microarray\.venv\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [101]:
print(confusion_matrix(y_test, svm_pred))

[[10  1  0  0  0]
 [ 0  2  0  0  0]
 [ 0  0  2  0  0]
 [ 0  0  0  3  0]
 [ 0  0  0  0  4]]


In [102]:
test_accuracy= accuracy_score(y_test, svm_pred)
test_accuracy * 100

95.45454545454545

In [103]:
train_accuracy = accuracy_score(y_train, svm_model.predict(X_train))
train_accuracy

1.0

In [104]:
print(classification_report(y_test, svm_pred))

              precision    recall  f1-score   support

           0       1.00      0.91      0.95        11
           1       0.67      1.00      0.80         2
           2       1.00      1.00      1.00         2
           3       1.00      1.00      1.00         3
           4       1.00      1.00      1.00         4

    accuracy                           0.95        22
   macro avg       0.93      0.98      0.95        22
weighted avg       0.97      0.95      0.96        22



Logistic Regression

In [105]:
from sklearn.linear_model import LogisticRegression

In [106]:
lgreg = LogisticRegression().fit(X_train, y_train)

In [107]:
lgreg_predict = lgreg.predict(X_test)

f:\leukemi_microarray\.venv\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [108]:
log_reg_test_accuracy = accuracy_score(y_test, lgreg_predict)
log_reg_test_accuracy

0.9545454545454546

In [109]:
log_reg_train_accuracy = accuracy_score(y_train, lgreg.predict(X_train))
log_reg_train_accuracy

1.0

In [110]:
print(classification_report(y_test, lgreg_predict))

              precision    recall  f1-score   support

           0       1.00      0.91      0.95        11
           1       0.67      1.00      0.80         2
           2       1.00      1.00      1.00         2
           3       1.00      1.00      1.00         3
           4       1.00      1.00      1.00         4

    accuracy                           0.95        22
   macro avg       0.93      0.98      0.95        22
weighted avg       0.97      0.95      0.96        22



In [111]:
print(confusion_matrix(y_test, lgreg_predict))

[[10  1  0  0  0]
 [ 0  2  0  0  0]
 [ 0  0  2  0  0]
 [ 0  0  0  3  0]
 [ 0  0  0  0  4]]


Linear Discriminant Analysis 

In [112]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [113]:
ld = LinearDiscriminantAnalysis().fit(X_train, y_train)

In [114]:
ld_predict = ld.predict(X_test)

f:\leukemi_microarray\.venv\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearDiscriminantAnalysis was fitted with feature names
  warnings.warn(


In [115]:
ld_test_accuracy_score = accuracy_score(y_test, ld_predict)
ld_test_accuracy_score

0.9545454545454546

In [116]:
ld_train_accuracy_score = accuracy_score(y_train, ld.predict(X_train))
ld_train_accuracy_score

1.0

In [123]:
print(classification_report(y_test, ld_predict))

              precision    recall  f1-score   support

           0       1.00      0.91      0.95        11
           1       0.67      1.00      0.80         2
           2       1.00      1.00      1.00         2
           3       1.00      1.00      1.00         3
           4       1.00      1.00      1.00         4

    accuracy                           0.95        22
   macro avg       0.93      0.98      0.95        22
weighted avg       0.97      0.95      0.96        22



naive bayes

In [117]:
from sklearn.naive_bayes import GaussianNB

In [118]:
nb = GaussianNB().fit(X_train, y_train)

In [119]:
nb_pred = nb.predict(X_test)

f:\leukemi_microarray\.venv\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


In [120]:
print("Accuracy: ", accuracy_score(y_test, nb_pred))

Accuracy:  0.9090909090909091


In [121]:
nb_train_accuracy = accuracy_score(y_train, nb.predict(X_train))
nb_train_accuracy

1.0

In [122]:
print(classification_report(y_test, nb_pred))

              precision    recall  f1-score   support

           0       0.91      0.91      0.91        11
           1       0.67      1.00      0.80         2
           2       1.00      0.50      0.67         2
           3       1.00      1.00      1.00         3
           4       1.00      1.00      1.00         4

    accuracy                           0.91        22
   macro avg       0.92      0.88      0.88        22
weighted avg       0.92      0.91      0.91        22

